version: '3.8'

services:
  sql-database:
    container_name: kw-sql-database
    image: postgres:14.1
    environment:
      POSTGRES_USER: oidc-db-admin
      POSTGRES_PASSWORD: oidc-db-password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./docker/oidc-sql-database-init:/docker-entrypoint-initdb.d"
      - "kw-sql-database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      oidc-wildfly-network:
        aliases:
          - sql-database
          - sql-database.local

  oidc-keycloak:
    container_name: kw-oidc-keycloak
    image: quay.io/keycloak/keycloak:18.0.2-legacy
    command:
      - "-b=0.0.0.0"
      - "-bmanagement=0.0.0.0"
    environment:
      KEYCLOAK_USER: oidc-admin-user
      KEYCLOAK_PASSWORD: oidc-admin-password
      DB_VENDOR: postgres
      DB_ADDR: sql-database.local
      DB_PORT: 5432
      DB_DATABASE: oidc_keycloak
      DB_USER: oidc_keycloak
      DB_PASSWORD: oidc-keycloak-password
      JDBC_PARAMS:
    volumes:
      - "./docker/oidc-keycloak/scripts:/opt/jboss/startup-scripts"
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      oidc-wildfly-network:
        aliases:
          - oidc-keycloak.local
          - oidc-keycloak
    depends_on:
      - sql-database

networks:
  oidc-wildfly-network:

volumes:
  kw-sql-database: