version: '3.8'

services:
  sql-database:
    container_name: sql-database
    image: postgres:14.1
    environment:
      POSTGRES_USER: oidc-db-admin
      POSTGRES_PASSWORD: oidc-db-password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./docker/oidc-sql-database-init:/docker-entrypoint-initdb.d"
      - "./docker/oidc-sql-database-mounted:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      oidc-quarkus-network:
        aliases:
          - sql-database
          - sql-database.local

  oidc-keycloak:
    container_name: oidc-keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    command:
      - --config-file /opt/tool4devops/oidc/keycloak.conf start-dev --auto-build --db postgres
    environment:
      KEYCLOAK_ADMIN: oidc-admin-user
      KEYCLOAK_ADMIN_PASSWORD: oidc-admin-password
    volumes:
      - "./docker/oidc-keycloak/config:/opt/tool4devops/oidc"
    ports:
      - "8080:8080"
    networks:
      oidc-quarkus-network:
        aliases:
          - oidc-keycloak.local
          - oidc-keycloak
    depends_on:
      - sql-database

networks:
  oidc-quarkus-network:
